apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rke2-openstack-calico.name" . }}-cloud-config-secret
type: addons.cluster.x-k8s.io/resource-set
stringData:
  cloud-config.yaml: |-
{{ include "cloudConfig.innerSecret" . | indent 4 }}