{{ if .Values.sdnController.enabled }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: {{ include "rke2-openstack-calico.name" . }}-x509-certificate-exporter-helm
spec:
  version: "3.18.1"
  chartName: x509-certificate-exporter
  clusterSelector:
    matchLabels:
    {{- include "rke2-openstack-calico.labels" . | nindent 6 }}
  options:
    install:
      createNamespace: true
    timeout: 5m
    wait: true
    waitForJobs: true
  namespace: monitoring
  repoURL: oci://us-central1-docker.pkg.dev/whitestack/whitecruiser/marketplace/drummond
  credentials:
    key: config.json
    secret:
      name: {{ .Values.cluster.addonsRepoCredentials.secret.name}}
      namespace: {{ .Values.cluster.addonsRepoCredentials.secret.namespace}}
  valuesTemplate: |
    image:
      pullPolicy: IfNotPresent
    psp:
      create: false
    rbac:
      create: true
    podExtraLabels: { }
    hostPathsExporter:
      podAnnotations: { }
      watchDirectories: [ ]
      watchFiles: [ ]
      watchKubeconfFiles: [ ]
      daemonSets:
        cp:
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
              operator: Exists
    rbacProxy:
      enabled: false
    {{- if and (hasKey .Values.x509CertExporter "customValues") (not (empty .Values.x509CertExporter.customValues)) }}
    {{- toYaml .Values.x509CertExporter.customValues }}
    {{- end }}
{{- end }}