{{- range $index, $worker := .Values.workerNodes.nodes }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ $.Values.cluster.name }}-worker-{{ $worker.name }}
  namespace: fleet-default
  labels:
    cluster.x-k8s.io/cluster-name: {{ $.Values.cluster.name }}
    cluster.x-k8s.io/role: worker
    whitestack.worker/node-group-name: "{{ $worker.name }}"
  {{- include "rke2-openstack-cilium.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      identityRef:
        name: {{ $.Values.cluster.name }}-cloud-config
        cloudName: openstack
      flavor: {{ $worker.flavorName | default $.Values.workerNodes.defaults.flavorName }}
      image:
        filter:
          name: {{ $.Values.workerNodes.imageName }}
      ports:
        - network:
            filter:
              name: {{ $.Values.infraConfig.principalNetwork.netName }}
        {{- if hasKey $worker "additionalPorts" }}
        {{- range $worker.additionalPorts }}
        - network:
            filter:
              name: {{ .netName }}
          fixedIPs:
            - subnet:
                filter:
                  name: {{ .subnetName }}
        {{- end }}
        {{- else }}
        {{- range $.Values.workerNodes.defaults.additionalPorts }}
        - network:
            filter:
              name: {{ .netName }}
          fixedIPs:
            - subnet:
                filter:
                  name: {{ .subnetName }}
        {{- end }}
        {{- end }}
      # Nombre de la clave SSH para acceder a la instancia
      sshKeyName: {{ $.Values.infraConfig.keypairName }}

      # Grupos de seguridad a nivel de máquina - opcional
      {{- if $.Values.workerNodes.defaults.securityGroups }}
      securityGroups:
        {{- range $.Values.workerNodes.defaults.securityGroups }}
        - filter:
            name: {{ . }}
        {{- end }}
      {{- end }}

      serverMetadata:
        - key: cluster
          value: {{ $.Values.cluster.name }}
      # Etiquetas para los recursos de OpenStack
      tags:
      - {{ $.Values.cluster.name }}
      - worker

      # Habilitar Config Drive para metadatos - opcional
      configDrive: true
      {{- if or (ne $.Values.workerNodes.defaults.hypervisorHostname "") (and (hasKey $worker "hypervisorHostname") (ne $worker.hypervisorHostname "")) }}
      schedulerHintAdditionalProperties:
        - name: "query"
          value:
            type: "String"
            string: "[\"=\", \"$hypervisor_hostname\", \"{{ $worker.hypervisorHostname | default $.Values.controlPlaneNodes.hypervisorHostname }}\"]"
      {{- end }}
      {{- $rootVolumeSize := dig "rootVolume" "sizeGiB" "" $worker | default (dig "rootVolume" "sizeGiB" "" $.Values.workerNodes.defaults) }}
      {{- if $rootVolumeSize }}
        {{- $sizeInt := int $rootVolumeSize }}
        {{- if lt $sizeInt 1 }}
          {{- fail "rootVolume.sizeGiB must be positive" }}
        {{- end }}

      rootVolume:
        sizeGiB: {{ $sizeInt }}

        {{- $az := dig "rootVolume" "availabilityZone" "" $worker | default (dig "rootVolume" "availabilityZone" "" $.Values.workerNodes.defaults) }}
        {{- if $az }}
        availabilityZone:
          name: {{ $az }}
        {{- end }}
      {{- end }}
{{/*      # Grupo de servidores para colocación - opcional*/}}
{{/*      serverGroup:*/}}
{{/*        filter:*/}}
{{/*          name: anti-affinity-group*/}}

{{/*      # Propiedades adicionales para el scheduler de OpenStack - opcional*/}}
{{/*      schedulerHintAdditionalProperties:*/}}
{{/*      - name: group*/}}
{{/*        value:*/}}
{{/*          type: String*/}}
{{/*          string: control-plane-group*/}}
{{- end }}