{{ if .Values.metallb.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: {{ include "rke2-baremetal-calico.name" . }}-metallb
  namespace: fleet-default
spec:
  version: "0.14.5"
  chart: metallb
  defaultNamespace: metallb-system
  releaseName: metallb
  repoName: "whitecruiser-apps"
  targets:
    - clusterName: {{ .Values.cluster.name }}
{{- if not (empty .Values.metallb.customValues) }}
  values:
{{- toYaml .Values.metallb.customValues | nindent 4 }}
{{- end }}
{{- end }}