{{ if .Values.nodeConfigOperator.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: {{ include "rke2-baremetal-calico.name" . }}-nco
  namespace: fleet-default
spec:
  version: "0.2.0"
  chart: node-config-operator
  defaultNamespace: nco-system
  releaseName: node-config-operator
  repoName: "whitecruiser-apps"
  values:
    {{- if and (hasKey .Values.nodeConfigOperator "customValues") (not (empty .Values.nodeConfigOperator.customValues)) }}
    {{- toYaml .Values.nodeConfigOperator.customValues }}
    {{- end }}
    managerConfig:
      aptEnabled: {{ .Values.nodeConfigOperator.managerConfig.aptEnabled }}
      hostfsEnabled: {{ .Values.nodeConfigOperator.managerConfig.hostfsEnabled }}
{{- end }}