{{ if .Values.sdnController.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: {{ include "rke2-baremetal-calico.name" . }}-sdn-controller
  namespace: fleet-default
spec:
  version: "0.3.0"
  chart: whitesdn-controller
  defaultNamespace: whitesdn
  releaseName: whitesdn-controller
  repoName: "whitecruiser-apps"
  targets:
    - clusterName: {{ .Values.cluster.name }}
  values:
{{- if and (hasKey .Values.sdnController "customValues") (not (empty .Values.sdnController.customValues)) }}
{{- toYaml .Values.sdnController.customValues | nindent 4 }}
{{- else }}
    whitesdnSecrets:
      password: {{ .Values.sdnController.whitesdnSecrets.password }}
{{- end }}
{{- end }}