apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: {{ .Values.cluster.name }}-cloud-config
  namespace: fleet-default
  annotations:
    "helm.sh/hook": pre-install,post-delete
type: Opaque
stringData:
{{- if not ( eq .Values.infraConfig.caCerts.configMap.name "") }}
  cacert: |-
    {{ (lookup "v1" "ConfigMap" .Values.infraConfig.caCerts.configMap.namespace .Values.infraConfig.caCerts.configMap.name).data.cacert }}
{{- end }}
  clouds.yaml: |-
    clouds:
      openstack:
        auth:
          auth_url: {{ .Values.infraConfig.authUrl }}
          username: {{ .Values.infraConfig.username }}
          password: {{ (lookup "v1" "Secret" .Values.infraConfig.password.secret.namespace .Values.infraConfig.password.secret.name).data.password | b64dec }}
          project_name: {{ .Values.infraConfig.tenantName }}
          user_domain_name: {{ .Values.infraConfig.domainName }}
          domain_name: {{ .Values.infraConfig.domainName }}
        region_name: {{ .Values.infraConfig.region }}
        interface: "public"
        identity_api_version: 3