apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: fleet-default
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
spec:
  identityRef:
    name: {{ .Values.cluster.name }}-cloud-config
    cloudName: openstack

  # Configuracion de red interna
  network:
    filter:
      name: {{ .Values.infraConfig.principalNetwork.netName }}

  # Configuración de subred
  subnets:
    - filter:
        name: {{ .Values.infraConfig.principalNetwork.subnetName }}

  controlPlaneAvailabilityZones:
  {{- range $.Values.infraConfig.availabilityZones }}
    - {{ . }}
  {{- end }}

  # Configuración del balanceador de carga para el API server
  apiServerLoadBalancer:
    enabled: false
  disableAPIServerFloatingIP: true
  disableExternalNetwork: true
  apiServerFixedIP: {{ .Values.cluster.apiServerVIP }}
{{/*  externalNetwork:*/}}
{{/*    filter:*/}}
{{/*      name: {{ .Values.infraConfig.externalNetwork.netName }}*/}}
