kube_version: 1.30.2
controlPlane:
  replicas: 1
  nodeSelector:
    whitestack.com/hostedcp: "true"
  tolerations:
    - key: "whitestack.com/hostedcp"  
      operator: "Equal"
      value: "true"
      effect: NoSchedule
calico:
  enabled: true
  mtu: 1430
kubeadmWorkers:
  enabled: true
  replicas: 2
  imageId: 178d1438-a74c-46c5-b244-be6aa0dae8e6
k0sWorkers:
  enabled: false
  replicas: 1
  imageId: 178d1438-a74c-46c5-b244-be6aa0dae8e6
cloudConfig:
  networkId: f7bd4a54-8208-4bf7-93ea-fcb1478d27b5
  subnetId: cf17fef5-9b75-40bf-ae19-0d1ecfb55c00
  sshKeyName: rancher
cloudCredentials:
  authUrl: "http://10.100.1.22:5000/v3"
  username: gcuba
  region: RegionOne
  project: gcuba
  domain: Default
  password:
    secretName: ocp2-gcuba
    secretNamespace: default