{{ if or .Values.monitoring.enabled .Values.x509CertExporter.enabled .Values.nodeConfigOperator.enabled }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: {{ include "rke2-openstack-calico.name" . }}-monitoring-crd
spec:
  version: "106.1.1-up69.8.2-rancher.5"
  chartName: rancher-monitoring-crd
  clusterSelector:
    matchLabels:
    {{- include "rke2-openstack-calico.labels" . | nindent 6 }}
  options:
    install:
      createNamespace: true
    timeout: 5m
    wait: true
    waitForJobs: true
  namespace: cattle-monitoring-system
  repoURL: oci://us-central1-docker.pkg.dev/whitestack/whitecruiser/marketplace/drummond
  credentials:
    key: config.json
    secret:
      name: {{ .Values.cluster.addonsRepoCredentials.secret.name}}
      namespace: {{ .Values.cluster.addonsRepoCredentials.secret.namespace}}
  {{- end }}