{{ if .Values.kubevirt.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: {{ include "rke2-baremetal-calico.name" . }}-kubevirt-cdi
  namespace: fleet-default
spec:
  version: "0.5.0"
  chart: cdi
  releaseName: cdi
  repoName: "whitecruiser-apps"
  defaultNamespace: kubevirt
  targets:
    - clusterName: {{ .Values.cluster.name }}
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: {{ include "rke2-baremetal-calico.name" . }}-kubevirt
  namespace: fleet-default
spec:
  version: "0.5.0"
  chart: kubevirt
  releaseName: kubevirt
  repoName: "whitecruiser-apps"
  defaultNamespace: kubevirt
  targets:
    - clusterName: {{ .Values.cluster.name }}
  values:
    kubevirt:
      configuration:
        developerConfiguration:
          useEmulation: true
    {{- if (not (empty .Values.kubevirt.customValues)) }}
    {{- toYaml .Values.kubevirt.customValues }}
    {{- end }}
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: {{ include "rke2-baremetal-calico.name" . }}-kubevirt-dashboard
  namespace: fleet-default
spec:
  version: 1.3.1
  chart: kubevirt-dashboard-extension
  releaseName: kubevirt-dashboard-extension
  repoName: "whitecruiser-apps"
  defaultNamespace: cattle-ui-plugin-system
  targets:
    - clusterName: {{ .Values.cluster.name }}
---
{{- end }}