{{ if .Values.logging.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: {{ include "rke2-baremetal-calico.name" . }}-loggin-crd
  namespace: fleet-default
spec:
  version: "106.0.1-up4.10.0-rancher.4"
  chart: rancher-logging-crd
  releaseName: rancher-logging-crd
  defaultNamespace: cattle-logging-system
  repoName: "whitecruiser-apps"
  targets:
    - clusterName: {{ .Values.cluster.name }}
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: {{ include "rke2-baremetal-calico.name" . }}-loggin
  namespace: fleet-default
spec:
  version: "106.0.1-up4.10.0-rancher.4"
  chart: rancher-logging
  releaseName: rancher-logging
  defaultNamespace: cattle-logging-system
  repoName: "whitecruiser-apps"
  targets:
    - clusterName: {{ .Values.cluster.name }}
  values:
{{- if and (hasKey .Values.logging "customValues") (not (empty .Values.logging.customValues)) }}
{{- toYaml .Values.logging.customValues | nindent 4}}
{{- else }}
    rke2:
      enabled: true
    logging:
      enableRecreateWorkloadOnImmutableFieldChange: true
      enabled: true
      clusterFlows:
        - name: all-logs
          spec:
            filters:
              - record_modifier:
                  records:
                    - cluster-name: {{ .Values.cluster.name }}
            globalOutputRefs:
              - fluentd-forward
            match:
              - select: {}
      fluentd:
        bufferStorageVolume:
          pvc:
            spec:
             accessModes:
               - ReadWriteOnce
             resources:
               requests:
                 storage: 5Gi
      clusterOutputs:
        - name: fluentd-forward
          spec:
            forward:
              buffer:
                flush_interval: 10s
                retry_forever: false
                retry_max_interval: '30'
                type: file
              compress: gzip
              require_ack_response: false
              servers:
                - host: {{ .Values.logging.clusterOutputs.server.host }}
                  port: {{ .Values.logging.clusterOutputs.server.port }}
              tls_insecure_mode: true
    hostTailer:
      enabled: true
      fileTailers:
        - name: syslog
          path: /var/log/syslog
{{- end }}
{{- end }}