apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ include "kamaji-openstack.fullname" . }}-cloud-config
spec:
  clusterSelector:
    matchLabels:
    {{- include "kamaji-openstack.labels" . | nindent 6 }}
  resources:
  - kind: Secret
    name: {{ include "kamaji-openstack.fullname" . }}-cloud-config-secret
  strategy: Reconcile