{{- if .Values.kubeadmWorkers.enabled }}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ include "kamaji-openstack.fullname" . }}-md-kubeadm
  labels:
  {{- include "kamaji-openstack.labels" . | nindent 4 }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
{{- end }}