apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kamaji-openstack.fullname" . }}-cloud-secret
  annotations:
    "helm.sh/hook": pre-install,post-delete
type: Opaque
stringData:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: {{ .Values.cloudCredentials.authUrl }}
          username: {{ .Values.cloudCredentials.username }}
          password: {{ (lookup "v1" "Secret" .Values.cloudCredentials.password.secretNamespace .Values.cloudCredentials.password.secretName).data.password | b64dec }}
          project_name: {{ .Values.cloudCredentials.project }}
          user_domain_name: {{ .Values.cloudCredentials.domain }}
          domain_name: {{ .Values.cloudCredentials.domain }}
        region_name: {{ .Values.cloudCredentials.region }}
        interface: "public"
        identity_api_version: 3
