{{- if .Values.k0sWorkers.enabled }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ include "kamaji-openstack.fullname" . }}-md-k0s
  labels:
  {{- include "kamaji-openstack.labels" . | nindent 4 }}
spec:
  template:
    spec:
      flavor: whiteidam
      identityRef:
        cloudName: openstack
        name: {{ include "kamaji-openstack.fullname" . }}-cloud-secret
      image:
        id: { .Values.k0s.imageId }}
      ports:
      - network:
          id: {{ .Values.cloudConfig.networkId }}
      sshKeyName: {{ .Values.cloudConfig.sshKeyName }}
{{- end }}