{{ if .Values.storage.cinder.enabled }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: {{ include "rke2-openstack-calico.name" . }}-longhorn
spec:
  chartName: openstack-cinder-csi
  version: 2.1.1
  clusterSelector:
    matchLabels:
    {{- include "rke2-openstack-calico.labels" . | nindent 6 }}
  options:
    install:
      createNamespace: true
    timeout: 5m
    wait: true
    waitForJobs: true
  namespace: kube-system
  repoURL: oci://us-central1-docker.pkg.dev/whitestack/whitecruiser/marketplace/drummond
  credentials:
    key: config.json
    secret:
      name: {{ .Values.cluster.addonsRepoCredentials.secret.name}}
      namespace: {{ .Values.cluster.addonsRepoCredentials.secret.namespace}}
  valuesTemplate: |
    {{- if and (hasKey .Values.storage "cinder") (hasKey .Values.storage.cinder "customValues") (not (empty .Values.storage.cinder.customValues)) }}
    {{- toYaml .Values.storage.cinder.customValues }}
    {{- end }}
    secret:
      enabled: true
      name: cloud-config
{{- end }}